### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by adminxh** [Rocket1184/electron-netease-cloud-music#134]
import { join } from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Module._compile (D:\electron-study-project\electron-netease-cloud-music-master\electron-netease-cloud-music-master\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Object.newLoader [as .js] (D:\electron-study-project\electron-netease-cloud-music-master\electron-netease-cloud-music-master\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)

**Comment by rocka** [comment]
What did you do? What do you expect to see?
